name: "Run code analysis on .NET source code"

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  analysis:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x.x'

    - name: Run NuGet restore
      run: dotnet restore

    # Run code analysis for all projects/solutions, such that code analysis violations break the build.
    - name: Run .NET Code Analysis
      uses: dotnet/code-analysis@d3a5cb6ef8547e36e87c4378cc3e982d9fe1afe7
      id: code-analysis
      with:
        build-breaking: true
